; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=z80 < %s | FileCheck %s --check-prefixes=Z80
; RUN: llc -mtriple=ez80-code16 < %s | FileCheck %s --check-prefixes=EZ80-CODE16
; RUN: llc -mtriple=ez80 < %s | FileCheck %s --check-prefixes=EZ80

define i8 @get_reg_i8(i8 %a, i8 %b, i8 %c, i8 %d, i8 %e, i8 %f) {
; Z80-LABEL: get_reg_i8:
; Z80:       ; %bb.0: ; %entry
; Z80-NEXT:    ld a, h
; Z80-NEXT:    ret
; Z80-NEXT:    .section .text,"ax",@progbits
; Z80-NEXT:    .local .Lfunc_end0
; Z80-NEXT:  .Lfunc_end0:
; Z80-NEXT:    .size _get_reg_i8, .Lfunc_end0-_get_reg_i8
;
; EZ80-CODE16-LABEL: get_reg_i8:
; EZ80-CODE16:       ; %bb.0: ; %entry
; EZ80-CODE16-NEXT:    ld a, h
; EZ80-CODE16-NEXT:    ret
; EZ80-CODE16-NEXT:    .section .text,"ax",@progbits
; EZ80-CODE16-NEXT:    .local .Lfunc_end0
; EZ80-CODE16-NEXT:  .Lfunc_end0:
; EZ80-CODE16-NEXT:    .size _get_reg_i8, .Lfunc_end0-_get_reg_i8
;
; EZ80-LABEL: get_reg_i8:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld a, (iy + 18)
; EZ80-NEXT:    ret
; EZ80-NEXT:    .section .text,"ax",@progbits
; EZ80-NEXT:    .local .Lfunc_end0
; EZ80-NEXT:  .Lfunc_end0:
; EZ80-NEXT:    .size _get_reg_i8, .Lfunc_end0-_get_reg_i8
entry:
  ret i8 %f
}

define i8 @get_stack_i8(i8 %a, i8 %b, i8 %c, i8 %d, i8 %e, i8 %f, i8 %g) {
; Z80-LABEL: get_stack_i8:
; Z80:       ; %bb.0: ; %entry
; Z80-NEXT:    ld iy, 0
; Z80-NEXT:    add iy, sp
; Z80-NEXT:    ld a, (iy + 2)
; Z80-NEXT:    ret
; Z80-NEXT:    .section .text,"ax",@progbits
; Z80-NEXT:    .local .Lfunc_end1
; Z80-NEXT:  .Lfunc_end1:
; Z80-NEXT:    .size _get_stack_i8, .Lfunc_end1-_get_stack_i8
;
; EZ80-CODE16-LABEL: get_stack_i8:
; EZ80-CODE16:       ; %bb.0: ; %entry
; EZ80-CODE16-NEXT:    ld iy, 0
; EZ80-CODE16-NEXT:    add iy, sp
; EZ80-CODE16-NEXT:    ld a, (iy + 2)
; EZ80-CODE16-NEXT:    ret
; EZ80-CODE16-NEXT:    .section .text,"ax",@progbits
; EZ80-CODE16-NEXT:    .local .Lfunc_end1
; EZ80-CODE16-NEXT:  .Lfunc_end1:
; EZ80-CODE16-NEXT:    .size _get_stack_i8, .Lfunc_end1-_get_stack_i8
;
; EZ80-LABEL: get_stack_i8:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld a, (iy + 21)
; EZ80-NEXT:    ret
; EZ80-NEXT:    .section .text,"ax",@progbits
; EZ80-NEXT:    .local .Lfunc_end1
; EZ80-NEXT:  .Lfunc_end1:
; EZ80-NEXT:    .size _get_stack_i8, .Lfunc_end1-_get_stack_i8
entry:
  ret i8 %g
}

define i16 @get_reg_i16(i16 %a, i16 %b, i16 %c) {
; Z80-LABEL: get_reg_i16:
; Z80:       ; %bb.0: ; %entry
; Z80-NEXT:    ret
; Z80-NEXT:    .section .text,"ax",@progbits
; Z80-NEXT:    .local .Lfunc_end2
; Z80-NEXT:  .Lfunc_end2:
; Z80-NEXT:    .size _get_reg_i16, .Lfunc_end2-_get_reg_i16
;
; EZ80-CODE16-LABEL: get_reg_i16:
; EZ80-CODE16:       ; %bb.0: ; %entry
; EZ80-CODE16-NEXT:    ret
; EZ80-CODE16-NEXT:    .section .text,"ax",@progbits
; EZ80-CODE16-NEXT:    .local .Lfunc_end2
; EZ80-CODE16-NEXT:  .Lfunc_end2:
; EZ80-CODE16-NEXT:    .size _get_reg_i16, .Lfunc_end2-_get_reg_i16
;
; EZ80-LABEL: get_reg_i16:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld hl, (iy + 9)
; EZ80-NEXT:    ; kill: def $hl killed $hl killed $uhl
; EZ80-NEXT:    ret
; EZ80-NEXT:    .section .text,"ax",@progbits
; EZ80-NEXT:    .local .Lfunc_end2
; EZ80-NEXT:  .Lfunc_end2:
; EZ80-NEXT:    .size _get_reg_i16, .Lfunc_end2-_get_reg_i16
entry:
  ret i16 %c
}

define i16 @get_stack_i16(i16 %a, i16 %b, i16 %c, i16 %d) {
; Z80-LABEL: get_stack_i16:
; Z80:       ; %bb.0: ; %entry
; Z80-NEXT:    ld iy, 0
; Z80-NEXT:    add iy, sp
; Z80-NEXT:    ld l, (iy + 2)
; Z80-NEXT:    ld h, (iy + 3)
; Z80-NEXT:    ret
; Z80-NEXT:    .section .text,"ax",@progbits
; Z80-NEXT:    .local .Lfunc_end3
; Z80-NEXT:  .Lfunc_end3:
; Z80-NEXT:    .size _get_stack_i16, .Lfunc_end3-_get_stack_i16
;
; EZ80-CODE16-LABEL: get_stack_i16:
; EZ80-CODE16:       ; %bb.0: ; %entry
; EZ80-CODE16-NEXT:    ld iy, 0
; EZ80-CODE16-NEXT:    add iy, sp
; EZ80-CODE16-NEXT:    ld hl, (iy + 2)
; EZ80-CODE16-NEXT:    ret
; EZ80-CODE16-NEXT:    .section .text,"ax",@progbits
; EZ80-CODE16-NEXT:    .local .Lfunc_end3
; EZ80-CODE16-NEXT:  .Lfunc_end3:
; EZ80-CODE16-NEXT:    .size _get_stack_i16, .Lfunc_end3-_get_stack_i16
;
; EZ80-LABEL: get_stack_i16:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld hl, (iy + 12)
; EZ80-NEXT:    ; kill: def $hl killed $hl killed $uhl
; EZ80-NEXT:    ret
; EZ80-NEXT:    .section .text,"ax",@progbits
; EZ80-NEXT:    .local .Lfunc_end3
; EZ80-NEXT:  .Lfunc_end3:
; EZ80-NEXT:    .size _get_stack_i16, .Lfunc_end3-_get_stack_i16
entry:
  ret i16 %d
}
