; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ez80 < %s | FileCheck %s --check-prefixes=EZ80

@global24 = external global i24

define i24 @load.global24() {
; EZ80-LABEL: load.global24:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld hl, (_global24)
; EZ80-NEXT:    ret
; EZ80-NEXT:    .section .text,"ax",@progbits
; EZ80-NEXT:    .local .Lfunc_end0
; EZ80-NEXT:  .Lfunc_end0:
; EZ80-NEXT:    .size _load.global24, .Lfunc_end0-_load.global24
entry:
  %val = load i24, i24* @global24, align 1
  ret i24 %val
}

define void @store.global24(i24 %val) {
; EZ80-LABEL: store.global24:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld hl, (iy + 3)
; EZ80-NEXT:    ld (_global24), hl
; EZ80-NEXT:    ret
; EZ80-NEXT:    .section .text,"ax",@progbits
; EZ80-NEXT:    .local .Lfunc_end1
; EZ80-NEXT:  .Lfunc_end1:
; EZ80-NEXT:    .size _store.global24, .Lfunc_end1-_store.global24
entry:
  store i24 %val, i24* @global24, align 1
  ret void
}

define i24 @load.with.gep(i24* %base, i16 %offset) {
; EZ80-LABEL: load.with.gep:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    push ix
; EZ80-NEXT:    ld ix, 0
; EZ80-NEXT:    add ix, sp
; EZ80-NEXT:    ld iy, (ix + 6)
; EZ80-NEXT:    ld de, (ix + 9)
; EZ80-NEXT:    ld a, d
; EZ80-NEXT:    ld l, a
; EZ80-NEXT:    rlc l
; EZ80-NEXT:    sbc hl, hl
; EZ80-NEXT:    ld h, a
; EZ80-NEXT:    ld l, e
; EZ80-NEXT:    ld bc, 3
; EZ80-NEXT:    call __imulu
; EZ80-NEXT:    push hl
; EZ80-NEXT:    pop de
; EZ80-NEXT:    add iy, de
; EZ80-NEXT:    ld hl, (iy)
; EZ80-NEXT:    pop ix
; EZ80-NEXT:    ret
; EZ80-NEXT:    .section .text,"ax",@progbits
; EZ80-NEXT:    .local .Lfunc_end2
; EZ80-NEXT:  .Lfunc_end2:
; EZ80-NEXT:    .size _load.with.gep, .Lfunc_end2-_load.with.gep
entry:
  %idx = sext i16 %offset to i32
  %ptr = getelementptr i24, i24* %base, i32 %idx
  %val = load i24, i24* %ptr, align 1
  ret i24 %val
}

define void @pair.store(i24* %dst, i24 %lo, i24 %hi) {
; EZ80-LABEL: pair.store:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    push ix
; EZ80-NEXT:    ld ix, 0
; EZ80-NEXT:    add ix, sp
; EZ80-NEXT:    ld iy, (ix + 6)
; EZ80-NEXT:    ld hl, (ix + 9)
; EZ80-NEXT:    ld de, (ix + 12)
; EZ80-NEXT:    ld (iy), hl
; EZ80-NEXT:    ld (iy + 3), de
; EZ80-NEXT:    pop ix
; EZ80-NEXT:    ret
; EZ80-NEXT:    .section .text,"ax",@progbits
; EZ80-NEXT:    .local .Lfunc_end3
; EZ80-NEXT:  .Lfunc_end3:
; EZ80-NEXT:    .size _pair.store, .Lfunc_end3-_pair.store
entry:
  store i24 %lo, i24* %dst, align 1
  %next = getelementptr inbounds i24, i24* %dst, i32 1
  store i24 %hi, i24* %next, align 1
  ret void
}
