; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s --check-prefix=OPT
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s --check-prefix=NOOPT

; Basic test to ensure the pass functions in some capacity
define void @test_repeated_stores() {
;
; OPT-LABEL: test_repeated_stores:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4096
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end0
; OPT-NEXT:  .Lfunc_end0:
; OPT-NEXT:    .size _test_repeated_stores, .Lfunc_end0-_test_repeated_stores
entry:
  store volatile i8 1, i8* inttoptr (i64 4096 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4096 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4096 to i8*)
  ret void
}

; Test to make sure that it only optimizes things that it should
define void @test_different_addresses() {
;
; NOOPT-LABEL: test_different_addresses:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ld a, 1
; NOOPT-NEXT:    ld l, 2
; NOOPT-NEXT:    ld e, 3
; NOOPT-NEXT:    ld (4096), a
; NOOPT-NEXT:    ld a, l
; NOOPT-NEXT:    ld (4097), a
; NOOPT-NEXT:    ld a, e
; NOOPT-NEXT:    ld (4098), a
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end1
; NOOPT-NEXT:  .Lfunc_end1:
; NOOPT-NEXT:    .size _test_different_addresses, .Lfunc_end1-_test_different_addresses
entry:
  store volatile i8 1, i8* inttoptr (i64 4096 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4097 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4098 to i8*)
  ret void
}
