; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Test make sure that the optimization pass works correctly
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s

; This is the C code `for (int i = 0; i < 256; i++) { *(volatile char*)0x8000 = i; }`

define void @c_style_loop_example() {
; CHECK-LABEL: c_style_loop_example:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    push ix
; CHECK-NEXT:    ld ix, 0
; CHECK-NEXT:    add ix, sp
; CHECK-NEXT:    push iy
; CHECK-NEXT:    ld de, 0
; CHECK-NEXT:    ld bc, 256
; CHECK-NEXT:    ld iyl, e
; CHECK-NEXT:    ld iyh, d
; CHECK-NEXT:    ex de, hl
; CHECK-NEXT:    .local .LBB0_1
; CHECK-NEXT:  .LBB0_1: ; %for.body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld a, iyl
; CHECK-NEXT:    ld (-32768), a
; CHECK-NEXT:    ld de, 1
; CHECK-NEXT:    add iy, de
; CHECK-NEXT:    push iy
; CHECK-NEXT:    ex (sp), hl
; CHECK-NEXT:    ld (ix - 2), l
; CHECK-NEXT:    ld (ix - 1), h
; CHECK-NEXT:    pop hl
; CHECK-NEXT:    dec de
; CHECK-NEXT:    adc hl, de
; CHECK-NEXT:    ld e, l
; CHECK-NEXT:    ld d, h
; CHECK-NEXT:    ex de, hl
; CHECK-NEXT:    ld e, iyl
; CHECK-NEXT:    ld d, iyh
; CHECK-NEXT:    ex de, hl
; CHECK-NEXT:    ld iy, 0
; CHECK-NEXT:    call __lcmpu
; CHECK-NEXT:    ex de, hl
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld l, (ix - 2)
; CHECK-NEXT:    ld h, (ix - 1)
; CHECK-NEXT:    ex (sp), hl
; CHECK-NEXT:    pop iy
; CHECK-NEXT:    jr nz, .LBB0_1
; CHECK-NEXT:  ; %bb.2: ; %for.end
; CHECK-NEXT:    ld sp, ix
; CHECK-NEXT:    pop ix
; CHECK-NEXT:    ret
; CHECK-NEXT:    .section .text,"ax",@progbits
; CHECK-NEXT:    .local .Lfunc_end0
; CHECK-NEXT:  .Lfunc_end0:
; CHECK-NEXT:    .size _c_style_loop_example, .Lfunc_end0-_c_style_loop_example

entry:
  br label %for.body

for.body:                                         ; preds = %for.body, %entry
  %i.08 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %conv = trunc i32 %i.08 to i8
  store volatile i8 %conv, i8* inttoptr (i64 32768 to i8*), align 1
  %inc = add nuw nsw i32 %i.08, 1
  %exitcond.not = icmp eq i32 %inc, 256
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:                                          ; preds = %for.body
  ret void
}

; This is what should be optimized - multiple stores within one block
define void @optimizable_sequential_stores() {
; CHECK-LABEL: optimizable_sequential_stores:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ld hl, -32768
; CHECK-NEXT:    ld (hl), 1
; CHECK-NEXT:    ld (hl), 3
; CHECK-NEXT:    ld (hl), 7
; CHECK-NEXT:    ret
; CHECK-NEXT:    .section .text,"ax",@progbits
; CHECK-NEXT:    .local .Lfunc_end1
; CHECK-NEXT:  .Lfunc_end1:
; CHECK-NEXT:    .size _optimizable_sequential_stores, .Lfunc_end1-_optimizable_sequential_stores

entry:
  store volatile i8 1, i8* inttoptr (i64 32768 to i8*), align 1
  store volatile i8 3, i8* inttoptr (i64 32768 to i8*), align 1
  store volatile i8 7, i8* inttoptr (i64 32768 to i8*), align 1
  ret void
}
