; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Test for the repeated store optimization pass to ensure it correctly handles
; different source registers, doesn't assume all stores are from register A,
; and properly handles HL register conflicts
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s --check-prefix=OPT
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s --check-prefix=NOOPT

; Test that 8-bit stores are correctly optimized with values moved to register A
define void @test_i8_stores_from_a() {
; All i8 stores go through register A, but HL conflict causes subsequence split
;
; OPT-LABEL: test_i8_stores_from_a:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4096
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end0
; OPT-NEXT:  .Lfunc_end0:
; OPT-NEXT:    .size _test_i8_stores_from_a, .Lfunc_end0-_test_i8_stores_from_a
entry:
  store volatile i8 1, i8* inttoptr (i64 4096 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4096 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4096 to i8*)
  ret void
}

; Test that 16-bit stores are handled correctly when HL conflicts exist
; This test verifies that optimization is correctly skipped when HL would conflict
define void @test_i16_stores() {
; Since HL is commonly used as source for 16-bit values, optimization is prevented
;
; NOOPT-LABEL: test_i16_stores:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ld hl, 1234
; NOOPT-NEXT:    ld de, 5678
; NOOPT-NEXT:    ld (8192), hl
; NOOPT-NEXT:    ld (8192), de
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end1
; NOOPT-NEXT:  .Lfunc_end1:
; NOOPT-NEXT:    .size _test_i16_stores, .Lfunc_end1-_test_i16_stores
entry:
  ; Store constant values - use HL as source, preventing optimization
  store volatile i16 1234, i16* inttoptr (i64 8192 to i16*)
  store volatile i16 5678, i16* inttoptr (i64 8192 to i16*)
  ret void
}

; Test mixed-size stores - HL is live (L used later), so no optimization with < 6 stores
define void @test_mixed_size_stores() {
; L register is used later, making HL live. Cost model requires 6+ stores when HL is live.
; Since there are only 3 stores, no optimization should occur.
;
; OPT-LABEL: test_mixed_size_stores:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 0
; OPT-NEXT:    add iy, sp
; OPT-NEXT:    push iy
; OPT-NEXT:    ld hl, 12288
; OPT-NEXT:    ld e, (iy - 2)
; OPT-NEXT:    ld d, (iy - 1)
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (12288), de
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    pop hl
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end2
; OPT-NEXT:  .Lfunc_end2:
; OPT-NEXT:    .size _test_mixed_size_stores, .Lfunc_end2-_test_mixed_size_stores
entry:
  %var = alloca i16
  %val = load i16, i16* %var
  store volatile i8 1, i8* inttoptr (i64 12288 to i8*)
  store volatile i16 %val, i16* inttoptr (i64 12288 to i16*)
  store volatile i8 2, i8* inttoptr (i64 12288 to i8*)
  ret void
}

; Test stores that should definitely be optimized - same type, same address
define void @test_consistent_i8_stores() {
; First store not optimized due to HL conflict, then 3 stores optimized together
;
; OPT-LABEL: test_consistent_i8_stores:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 16384
; OPT-NEXT:    ld (hl), 10
; OPT-NEXT:    ld (hl), 20
; OPT-NEXT:    ld (hl), 30
; OPT-NEXT:    ld (hl), 40
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end3
; OPT-NEXT:  .Lfunc_end3:
; OPT-NEXT:    .size _test_consistent_i8_stores, .Lfunc_end3-_test_consistent_i8_stores
entry:
  store volatile i8 10, i8* inttoptr (i64 16384 to i8*)
  store volatile i8 20, i8* inttoptr (i64 16384 to i8*)
  store volatile i8 30, i8* inttoptr (i64 16384 to i8*)
  store volatile i8 40, i8* inttoptr (i64 16384 to i8*)
  ret void
}

; Test that the cost model is applied correctly
define void @test_cost_model_single_store() {
; Single stores should not be optimized
;
; NOOPT-LABEL: test_cost_model_single_store:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ld a, 42
; NOOPT-NEXT:    ld (20480), a
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end4
; NOOPT-NEXT:  .Lfunc_end4:
; NOOPT-NEXT:    .size _test_cost_model_single_store, .Lfunc_end4-_test_cost_model_single_store
entry:
  store volatile i8 42, i8* inttoptr (i64 20480 to i8*)
  ret void
}

; Test function with multiple separate sequences
define void @test_multiple_sequences() {
; Multiple subsequences with HL conflicts and liveness considerations
; First sequence: 2 stores, HL conflict breaks it, too short to optimize
; Second sequence: 3 stores, but HL is live (H=5), cost model says don't optimize (< 6 stores)
;
; OPT-LABEL: test_multiple_sequences:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 24576
; OPT-NEXT:    ld hl, 28672
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ld (hl), 4
; OPT-NEXT:    ld (hl), 5
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end5
; OPT-NEXT:  .Lfunc_end5:
; OPT-NEXT:    .size _test_multiple_sequences, .Lfunc_end5-_test_multiple_sequences
entry:
  ; First sequence
  store volatile i8 1, i8* inttoptr (i64 24576 to i8*)
  store volatile i8 2, i8* inttoptr (i64 24576 to i8*)

  ; Second sequence
  store volatile i8 3, i8* inttoptr (i64 28672 to i8*)
  store volatile i8 4, i8* inttoptr (i64 28672 to i8*)
  store volatile i8 5, i8* inttoptr (i64 28672 to i8*)
  ret void
}
