; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Comprehensive test suite for Z80 Repeated Store Optimization Pass
; Tests all edge cases, cost model scenarios, register conflicts, and liveness analysis
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s --check-prefix=OPT
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s --check-prefix=NOOPT

; ========== BASIC FUNCTIONALITY TESTS ==========

; Test 1: Basic two-store case with register allocation conflicts
; Register allocation causes HL conflict, so no optimization occurs
define void @test_basic_two_stores_register_conflict() {
;
; OPT-LABEL: test_basic_two_stores_register_conflict:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4096
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end0
; OPT-NEXT:  .Lfunc_end0:
; OPT-NEXT:    .size _test_basic_two_stores_register_conflict, .Lfunc_end0-_test_basic_two_stores_register_conflict
entry:
  store volatile i8 1, i8* inttoptr (i64 4096 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4096 to i8*)
  ret void
}

; Test 2: Single store should not be optimized
define void @test_single_store_no_opt() {
;
; NOOPT-LABEL: test_single_store_no_opt:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ld a, 42
; NOOPT-NEXT:    ld (4097), a
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end1
; NOOPT-NEXT:  .Lfunc_end1:
; NOOPT-NEXT:    .size _test_single_store_no_opt, .Lfunc_end1-_test_single_store_no_opt
entry:
  store volatile i8 42, i8* inttoptr (i64 4097 to i8*)
  ret void
}

; Test 3: Different addresses should not be optimized together
define void @test_different_addresses() {
;
; NOOPT-LABEL: test_different_addresses:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ld a, 1
; NOOPT-NEXT:    ld l, 2
; NOOPT-NEXT:    ld e, 3
; NOOPT-NEXT:    ld (4098), a
; NOOPT-NEXT:    ld a, l
; NOOPT-NEXT:    ld (4099), a
; NOOPT-NEXT:    ld a, e
; NOOPT-NEXT:    ld (4100), a
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end2
; NOOPT-NEXT:  .Lfunc_end2:
; NOOPT-NEXT:    .size _test_different_addresses, .Lfunc_end2-_test_different_addresses
entry:
  store volatile i8 1, i8* inttoptr (i64 4098 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4099 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4100 to i8*)
  ret void
}

; Test 4: Large sequence with register allocation conflicts
; Register allocation uses H and L registers, preventing optimization
define void @test_large_sequence_register_conflicts() {
;
; OPT-LABEL: test_large_sequence_register_conflicts:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4101
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ld (hl), 4
; OPT-NEXT:    ld (hl), l
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end3
; OPT-NEXT:  .Lfunc_end3:
; OPT-NEXT:    .size _test_large_sequence_register_conflicts, .Lfunc_end3-_test_large_sequence_register_conflicts
entry:
  store volatile i8 1, i8* inttoptr (i64 4101 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4101 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4101 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4101 to i8*)
  store volatile i8 5, i8* inttoptr (i64 4101 to i8*)
  ret void
}

; ========== COST MODEL TESTS ==========

; Test 5: HL live with 5 stores - should NOT optimize (< 6 threshold)
define i16 @test_hl_live_five_stores_no_opt() {
;
; OPT-LABEL: test_hl_live_five_stores_no_opt:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4102
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0x5678
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end4
; OPT-NEXT:  .Lfunc_end4:
; OPT-NEXT:    .size _test_hl_live_five_stores_no_opt, .Lfunc_end4-_test_hl_live_five_stores_no_opt
entry:
  %hl_input = call i16 asm "ld hl, 0x5678", "={hl}"()
  store volatile i8 1, i8* inttoptr (i64 4102 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4102 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4102 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4102 to i8*)
  store volatile i8 5, i8* inttoptr (i64 4102 to i8*)
  ret i16 %hl_input
}

; Test 6: HL live with exactly 6 stores - should optimize with PUSH/POP
define i16 @test_hl_live_six_stores_optimize() {
;
; OPT-LABEL: test_hl_live_six_stores_optimize:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4103
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0x1234
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end5
; OPT-NEXT:  .Lfunc_end5:
; OPT-NEXT:    .size _test_hl_live_six_stores_optimize, .Lfunc_end5-_test_hl_live_six_stores_optimize
entry:
  %hl_input = call i16 asm "ld hl, 0x1234", "={hl}"()
  store volatile i8 1, i8* inttoptr (i64 4103 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4103 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4103 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4103 to i8*)
  store volatile i8 5, i8* inttoptr (i64 4103 to i8*)
  store volatile i8 6, i8* inttoptr (i64 4103 to i8*)
  ret i16 %hl_input
}

; Test 7: HL live with 10 stores - should optimize with PUSH/POP
define i16 @test_hl_live_ten_stores_optimize() {
;
; OPT-LABEL: test_hl_live_ten_stores_optimize:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4104
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0xabcd
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ld (iy), 7
; OPT-NEXT:    ld (iy), 8
; OPT-NEXT:    ld (iy), 9
; OPT-NEXT:    ld (iy), 10
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end6
; OPT-NEXT:  .Lfunc_end6:
; OPT-NEXT:    .size _test_hl_live_ten_stores_optimize, .Lfunc_end6-_test_hl_live_ten_stores_optimize
entry:
  %hl_input = call i16 asm "ld hl, 0xabcd", "={hl}"()
  store volatile i8 1, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 5, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 6, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 7, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 8, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 9, i8* inttoptr (i64 4104 to i8*)
  store volatile i8 10, i8* inttoptr (i64 4104 to i8*)
  ret i16 %hl_input
}

; ========== HL CONFLICT TESTS ==========

; Test 8: HL conflict in the middle should split sequence
define i16 @test_hl_conflict_split() {
;
; OPT-LABEL: test_hl_conflict_split:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4105
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0x4321
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (4105), hl
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end7
; OPT-NEXT:  .Lfunc_end7:
; OPT-NEXT:    .size _test_hl_conflict_split, .Lfunc_end7-_test_hl_conflict_split
entry:
  %hl_value = call i16 asm "ld hl, 0x4321", "={hl}"()
  store volatile i8 1, i8* inttoptr (i64 4105 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4105 to i8*)
  store volatile i16 %hl_value, i16* inttoptr (i64 4105 to i16*)  ; HL conflict
  store volatile i8 3, i8* inttoptr (i64 4105 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4105 to i8*)
  ret i16 %hl_value
}

; Test 9: H register conflict should split sequence
define i8 @test_h_conflict_split() {
;
; OPT-LABEL: test_h_conflict_split:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4106
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld h, 0x55
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld (4106), a
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld a, h
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end8
; OPT-NEXT:  .Lfunc_end8:
; OPT-NEXT:    .size _test_h_conflict_split, .Lfunc_end8-_test_h_conflict_split
entry:
  %h_value = call i8 asm "ld h, 0x55", "={h}"()
  store volatile i8 1, i8* inttoptr (i64 4106 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4106 to i8*)
  call void asm sideeffect "ld (4106), a", "{h}"(i8 %h_value)  ; H register usage
  store volatile i8 3, i8* inttoptr (i64 4106 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4106 to i8*)
  ret i8 %h_value
}

; Test 10: L register conflict should split sequence
define i8 @test_l_conflict_split() {
;
; OPT-LABEL: test_l_conflict_split:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4107
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld l, 0xaa
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld (4107), a
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld a, l
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end9
; OPT-NEXT:  .Lfunc_end9:
; OPT-NEXT:    .size _test_l_conflict_split, .Lfunc_end9-_test_l_conflict_split
entry:
  %l_value = call i8 asm "ld l, 0xaa", "={l}"()
  store volatile i8 1, i8* inttoptr (i64 4107 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4107 to i8*)
  call void asm sideeffect "ld (4107), a", "{l}"(i8 %l_value)  ; L register usage
  store volatile i8 3, i8* inttoptr (i64 4107 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4107 to i8*)
  ret i8 %l_value
}

; Test 11: Multiple register conflicts should split sequence into unoptimized subsequences
define i16 @test_multiple_register_conflicts() {
;
; OPT-LABEL: test_multiple_register_conflicts:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4108
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld de, 0x1111
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ex de, hl
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld bc, 0x2222
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (4108), hl
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (4108), bc
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    add hl, bc
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end10
; OPT-NEXT:  .Lfunc_end10:
; OPT-NEXT:    .size _test_multiple_register_conflicts, .Lfunc_end10-_test_multiple_register_conflicts
entry:
  %de_value = call i16 asm "ld de, 0x1111", "={de}"()
  %bc_value = call i16 asm "ld bc, 0x2222", "={bc}"()

  store volatile i8 1, i8* inttoptr (i64 4108 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4108 to i8*)
  store volatile i16 %de_value, i16* inttoptr (i64 4108 to i16*)  ; First conflict (DE register)
  store volatile i8 3, i8* inttoptr (i64 4108 to i8*)
  store volatile i16 %bc_value, i16* inttoptr (i64 4108 to i16*)  ; Second conflict (BC register)
  store volatile i8 4, i8* inttoptr (i64 4108 to i8*)

  %combined = add i16 %de_value, %bc_value
  ret i16 %combined
}

; ========== 16-BIT AND 24-BIT STORE TESTS ==========

; Test 12: 16-bit stores with compatible registers
define void @test_16bit_stores_compatible() {
;
; OPT-LABEL: test_16bit_stores_compatible:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld de, 0x3333
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld bc, 0x4444
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld hl, 4109
; OPT-NEXT:    ld (hl), de
; OPT-NEXT:    ld (hl), bc
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end11
; OPT-NEXT:  .Lfunc_end11:
; OPT-NEXT:    .size _test_16bit_stores_compatible, .Lfunc_end11-_test_16bit_stores_compatible
entry:
  %de_val = call i16 asm "ld de, 0x3333", "={de}"()
  %bc_val = call i16 asm "ld bc, 0x4444", "={bc}"()
  store volatile i16 %de_val, i16* inttoptr (i64 4109 to i16*)
  store volatile i16 %bc_val, i16* inttoptr (i64 4109 to i16*)
  ret void
}

; Test 13: 16-bit stores with HL conflict (source is HL)
define void @test_16bit_stores_hl_source_conflict() {
;
; NOOPT-LABEL: test_16bit_stores_hl_source_conflict:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ;APP
; NOOPT-NEXT:    ld de, 0x5555
; NOOPT-NEXT:    ;NO_APP
; NOOPT-NEXT:    ;APP
; NOOPT-NEXT:    ld hl, 0x6666
; NOOPT-NEXT:    ;NO_APP
; NOOPT-NEXT:    ;APP
; NOOPT-NEXT:    ld bc, 0x7777
; NOOPT-NEXT:    ;NO_APP
; NOOPT-NEXT:    ld (4110), de
; NOOPT-NEXT:    ld (4110), hl
; NOOPT-NEXT:    ld (4110), bc
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end12
; NOOPT-NEXT:  .Lfunc_end12:
; NOOPT-NEXT:    .size _test_16bit_stores_hl_source_conflict, .Lfunc_end12-_test_16bit_stores_hl_source_conflict
entry:
  %de_val = call i16 asm "ld de, 0x5555", "={de}"()
  %hl_val = call i16 asm "ld hl, 0x6666", "={hl}"()
  %bc_val = call i16 asm "ld bc, 0x7777", "={bc}"()

  store volatile i16 %de_val, i16* inttoptr (i64 4110 to i16*)
  store volatile i16 %hl_val, i16* inttoptr (i64 4110 to i16*)  ; HL conflict
  store volatile i16 %bc_val, i16* inttoptr (i64 4110 to i16*)
  ret void
}

; Test 14: Mixed 8-bit and 16-bit stores
define void @test_mixed_8bit_16bit_stores() {
;
; OPT-LABEL: test_mixed_8bit_16bit_stores:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4111
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld de, 0x8888
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld bc, 0x9999
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (4111), de
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ld (4111), bc
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end13
; OPT-NEXT:  .Lfunc_end13:
; OPT-NEXT:    .size _test_mixed_8bit_16bit_stores, .Lfunc_end13-_test_mixed_8bit_16bit_stores
entry:
  %de_val = call i16 asm "ld de, 0x8888", "={de}"()
  %bc_val = call i16 asm "ld bc, 0x9999", "={bc}"()

  store volatile i8 1, i8* inttoptr (i64 4111 to i8*)
  store volatile i16 %de_val, i16* inttoptr (i64 4111 to i16*)
  store volatile i8 2, i8* inttoptr (i64 4111 to i8*)
  store volatile i16 %bc_val, i16* inttoptr (i64 4111 to i16*)
  ret void
}

; ========== LIVENESS ANALYSIS EDGE CASES ==========

; Test 15: HL used but not live at function end
define void @test_hl_used_not_live_at_end() {
;
; OPT-LABEL: test_hl_used_not_live_at_end:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4112
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0xaaaa
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld (0x2000), hl
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end14
; OPT-NEXT:  .Lfunc_end14:
; OPT-NEXT:    .size _test_hl_used_not_live_at_end, .Lfunc_end14-_test_hl_used_not_live_at_end
entry:
  %hl_temp = call i16 asm "ld hl, 0xaaaa", "={hl}"()
  call void asm sideeffect "ld (0x2000), hl", "{hl}"(i16 %hl_temp)  ; Use HL but don't return it

  store volatile i8 1, i8* inttoptr (i64 4112 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4112 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4112 to i8*)
  ret void
}

; Test 16: HL live through function calls
define i16 @test_hl_live_through_function_call() {
;
; OPT-LABEL: test_hl_live_through_function_call:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4113
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0xbbbb
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end15
; OPT-NEXT:  .Lfunc_end15:
; OPT-NEXT:    .size _test_hl_live_through_function_call, .Lfunc_end15-_test_hl_live_through_function_call
entry:
  %hl_input = call i16 asm "ld hl, 0xbbbb", "={hl}"()

  store volatile i8 1, i8* inttoptr (i64 4113 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4113 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4113 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4113 to i8*)
  store volatile i8 5, i8* inttoptr (i64 4113 to i8*)
  store volatile i8 6, i8* inttoptr (i64 4113 to i8*)

  ret i16 %hl_input
}

; Test 17: H register live prevents optimization (6 stores, no optimization)
define i8 @test_h_live_prevents_optimization() {
;
; OPT-LABEL: test_h_live_prevents_optimization:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4114
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld h, 0xcc
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld a, h
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end16
; OPT-NEXT:  .Lfunc_end16:
; OPT-NEXT:    .size _test_h_live_prevents_optimization, .Lfunc_end16-_test_h_live_prevents_optimization
entry:
  %h_input = call i8 asm "ld h, 0xcc", "={h}"()

  store volatile i8 1, i8* inttoptr (i64 4114 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4114 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4114 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4114 to i8*)
  store volatile i8 5, i8* inttoptr (i64 4114 to i8*)
  store volatile i8 6, i8* inttoptr (i64 4114 to i8*)

  ret i8 %h_input
}

; Test 18: L register live prevents optimization (6 stores, no optimization)
define i8 @test_l_live_prevents_optimization() {
;
; OPT-LABEL: test_l_live_prevents_optimization:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4115
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld l, 0xdd
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld a, l
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end17
; OPT-NEXT:  .Lfunc_end17:
; OPT-NEXT:    .size _test_l_live_prevents_optimization, .Lfunc_end17-_test_l_live_prevents_optimization
entry:
  %l_input = call i8 asm "ld l, 0xdd", "={l}"()

  store volatile i8 1, i8* inttoptr (i64 4115 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4115 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4115 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4115 to i8*)
  store volatile i8 5, i8* inttoptr (i64 4115 to i8*)
  store volatile i8 6, i8* inttoptr (i64 4115 to i8*)

  ret i8 %l_input
}

; ========== INSTRUCTION SEQUENCE INTERRUPTION TESTS ==========

; Test 19: Inline assembly that doesn't affect HL - sequence should NOT break
define void @test_inline_asm_breaks_sequence() {
;
; OPT-LABEL: test_inline_asm_breaks_sequence:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4116
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ;APP
; OPT-NEXT:    nop
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ld (hl), 4
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end18
; OPT-NEXT:  .Lfunc_end18:
; OPT-NEXT:    .size _test_inline_asm_breaks_sequence, .Lfunc_end18-_test_inline_asm_breaks_sequence
entry:
  store volatile i8 1, i8* inttoptr (i64 4116 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4116 to i8*)
  call void asm sideeffect "nop", ""()  ; Does not affect HL, sequence continues
  store volatile i8 3, i8* inttoptr (i64 4116 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4116 to i8*)
  ret void
}

; Test 19b: Inline assembly that DOES modify HL - should break sequence
define void @test_inline_asm_modifies_hl() {
;
; OPT-LABEL: test_inline_asm_modifies_hl:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4116
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0x1234
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end19
; OPT-NEXT:  .Lfunc_end19:
; OPT-NEXT:    .size _test_inline_asm_modifies_hl, .Lfunc_end19-_test_inline_asm_modifies_hl
entry:
  store volatile i8 1, i8* inttoptr (i64 4116 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4116 to i8*)
  call void asm sideeffect "ld hl, 0x1234", "~{hl}"()  ; Modifies HL, breaks sequence
  store volatile i8 3, i8* inttoptr (i64 4116 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4116 to i8*)
  ret void
}

; Test 20: Function call breaking sequence
declare void @external_function()

define void @test_function_call_breaks_sequence() {
;
; OPT-LABEL: test_function_call_breaks_sequence:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4117
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    call _external_function
; OPT-NEXT:    ld hl, 4117
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ld (hl), 4
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end20
; OPT-NEXT:  .Lfunc_end20:
; OPT-NEXT:    .size _test_function_call_breaks_sequence, .Lfunc_end20-_test_function_call_breaks_sequence
entry:
  store volatile i8 1, i8* inttoptr (i64 4117 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4117 to i8*)
  call void @external_function()  ; Breaks sequence
  store volatile i8 3, i8* inttoptr (i64 4117 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4117 to i8*)
  ret void
}

; Test 21: Memory load breaking sequence (HL modification)
define void @test_memory_load_breaks_sequence() {
;
; OPT-LABEL: test_memory_load_breaks_sequence:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4118
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ld de, (8000)
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ld (hl), 4
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end21
; OPT-NEXT:  .Lfunc_end21:
; OPT-NEXT:    .size _test_memory_load_breaks_sequence, .Lfunc_end21-_test_memory_load_breaks_sequence
entry:
  store volatile i8 1, i8* inttoptr (i64 4118 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4118 to i8*)
  %loaded = load volatile i16, i16* inttoptr (i64 8000 to i16*)  ; May modify HL
  store volatile i8 3, i8* inttoptr (i64 4118 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4118 to i8*)
  ret void
}

; ========== BOUNDARY AND EDGE CASE TESTS ==========

; Test 22: Maximum address values (no optimization for two stores)
define void @test_max_address_values_no_opt() {
;
; OPT-LABEL: test_max_address_values_no_opt:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, -1
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end22
; OPT-NEXT:  .Lfunc_end22:
; OPT-NEXT:    .size _test_max_address_values_no_opt, .Lfunc_end22-_test_max_address_values_no_opt
entry:
  store volatile i8 1, i8* inttoptr (i64 65535 to i8*)  ; Max 16-bit address
  store volatile i8 2, i8* inttoptr (i64 65535 to i8*)
  ret void
}

; Test 23: Zero address
define void @test_zero_address() {
;
; OPT-LABEL: test_zero_address:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 0
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end23
; OPT-NEXT:  .Lfunc_end23:
; OPT-NEXT:    .size _test_zero_address, .Lfunc_end23-_test_zero_address
entry:
  store volatile i8 1, i8* inttoptr (i64 0 to i8*)  ; Zero page
  store volatile i8 2, i8* inttoptr (i64 0 to i8*)
  ret void
}

; Test 24: Stores with skippable load instructions (should be optimized)
define void @test_non_consecutive_no_optimization() {
;
; OPT-LABEL: test_non_consecutive_no_optimization:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4119
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld a, (5000)
; OPT-NEXT:    ld (hl), a
; OPT-NEXT:    ld a, (5001)
; OPT-NEXT:    ld (hl), a
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end24
; OPT-NEXT:  .Lfunc_end24:
; OPT-NEXT:    .size _test_non_consecutive_no_optimization, .Lfunc_end24-_test_non_consecutive_no_optimization
entry:
  store volatile i8 1, i8* inttoptr (i64 4119 to i8*)
  ; Skippable instruction (load to A register)
  %temp1 = load volatile i8, i8* inttoptr (i64 5000 to i8*)
  store volatile i8 %temp1, i8* inttoptr (i64 4119 to i8*)
  ; Another skippable instruction
  %temp2 = load volatile i8, i8* inttoptr (i64 5001 to i8*)
  store volatile i8 %temp2, i8* inttoptr (i64 4119 to i8*)
  ret void
}

; Test 25: Very large store count with HL live (stress test)
define i16 @test_large_store_count_hl_live() {
;
; OPT-LABEL: test_large_store_count_hl_live:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 4120
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0xeeee
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ld (iy), 7
; OPT-NEXT:    ld (iy), 8
; OPT-NEXT:    ld (iy), 9
; OPT-NEXT:    ld (iy), 10
; OPT-NEXT:    ld (iy), 11
; OPT-NEXT:    ld (iy), 12
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end25
; OPT-NEXT:  .Lfunc_end25:
; OPT-NEXT:    .size _test_large_store_count_hl_live, .Lfunc_end25-_test_large_store_count_hl_live
entry:
  %hl_input = call i16 asm "ld hl, 0xeeee", "={hl}"()

  store volatile i8 1, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 3, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 5, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 6, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 7, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 8, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 9, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 10, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 11, i8* inttoptr (i64 4120 to i8*)
  store volatile i8 12, i8* inttoptr (i64 4120 to i8*)

  ret i16 %hl_input
}

; ========== MULTIPLE BASIC BLOCK TESTS ==========

; Test 26: Stores across basic blocks (should not optimize across blocks)
define void @test_stores_across_basic_blocks(i1 %cond) {
;
; OPT-LABEL: test_stores_across_basic_blocks:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4121
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    bit 0, e
; OPT-NEXT:    jr z, .LBB26_2
; OPT-NEXT:  ; %bb.1: ; %then
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    .local .LBB26_2
; OPT-NEXT:  .LBB26_2: ; %exit
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end26
; OPT-NEXT:  .Lfunc_end26:
; OPT-NEXT:    .size _test_stores_across_basic_blocks, .Lfunc_end26-_test_stores_across_basic_blocks
entry:
  store volatile i8 1, i8* inttoptr (i64 4121 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4121 to i8*)
  br i1 %cond, label %then, label %else

then:
  store volatile i8 3, i8* inttoptr (i64 4121 to i8*)
  br label %exit

else:
  ret void

exit:
  ret void
}

; Test 27: Stores in different basic blocks should be optimized separately
define void @test_stores_in_separate_blocks(i1 %cond) {
;
; OPT-LABEL: test_stores_in_separate_blocks:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4122
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    bit 0, e
; OPT-NEXT:    jr z, .LBB27_2
; OPT-NEXT:  ; %bb.1: ; %then
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ld (hl), 4
; OPT-NEXT:    .local .LBB27_2
; OPT-NEXT:  .LBB27_2: ; %else
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end27
; OPT-NEXT:  .Lfunc_end27:
; OPT-NEXT:    .size _test_stores_in_separate_blocks, .Lfunc_end27-_test_stores_in_separate_blocks
entry:
  store volatile i8 1, i8* inttoptr (i64 4122 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4122 to i8*)
  br i1 %cond, label %then, label %else

then:
  store volatile i8 3, i8* inttoptr (i64 4122 to i8*)
  store volatile i8 4, i8* inttoptr (i64 4122 to i8*)
  ret void

else:
  ret void
}

; ========== ERROR AND REGRESSION TESTS ==========

; Test 28: Empty function should not crash
define void @test_empty_function() {
;
; NOOPT-LABEL: test_empty_function:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end28
; NOOPT-NEXT:  .Lfunc_end28:
; NOOPT-NEXT:    .size _test_empty_function, .Lfunc_end28-_test_empty_function
entry:
  ret void
}

; Test 29: Function with only non-store instructions
define i8 @test_no_stores() {
;
; NOOPT-LABEL: test_no_stores:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ld a, (4123)
; NOOPT-NEXT:    inc a
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end29
; NOOPT-NEXT:  .Lfunc_end29:
; NOOPT-NEXT:    .size _test_no_stores, .Lfunc_end29-_test_no_stores
entry:
  %val = load volatile i8, i8* inttoptr (i64 4123 to i8*)
  %result = add i8 %val, 1
  ret i8 %result
}

; Test 30: Complex instruction pattern that should not be optimized
define void @test_complex_non_optimizable() {
;
; OPT-LABEL: test_complex_non_optimizable:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4124
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    call _external_function
; OPT-NEXT:    ld a, 2
; OPT-NEXT:    ld (4125), a
; OPT-NEXT:    ld hl, 4124
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end30
; OPT-NEXT:  .Lfunc_end30:
; OPT-NEXT:    .size _test_complex_non_optimizable, .Lfunc_end30-_test_complex_non_optimizable
entry:
  store volatile i8 1, i8* inttoptr (i64 4124 to i8*)  ; First store
  call void @external_function()                        ; Function call breaks sequence
  store volatile i8 2, i8* inttoptr (i64 4125 to i8*)  ; Different address
  store volatile i8 3, i8* inttoptr (i64 4124 to i8*)  ; Back to original address, but single store
  ret void
}
