; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; This test specifically targets the bug where Z80RepeatedStoreOptPass assumed
; all stores were from register A, causing incorrect transformations.
;
; This test ensures that different source registers are preserved correctly.
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s

; Test using inline assembly - these should NOT be optimized since inline asm is opaque
define void @test_register_preservation_bug() {
; CHECK-LABEL: test_register_preservation_bug:
; CHECK:       ; %bb.0: ; %entry
; CHECK:          ;APP
; CHECK:          ld b, 10
; CHECK:          ld (4096), b
; CHECK:          ld c, 20
; CHECK:          ld (4096), c
; CHECK:          ld d, 30
; CHECK:          ld (4096), d
; CHECK:          ;NO_APP
; CHECK-NEXT:    ret
; CHECK-NEXT:    .section .text,"ax",@progbits
; CHECK-NEXT:    .local .Lfunc_end0
; CHECK-NEXT:  .Lfunc_end0:
; CHECK-NEXT:    .size _test_register_preservation_bug, .Lfunc_end0-_test_register_preservation_bug
; Inline assembly should remain unchanged - optimization pass can't see inside it

entry:
  ; Use inline assembly to create stores that remain unoptimized
  ; The optimization pass cannot see inside inline assembly blocks
  call void asm sideeffect "
    ld b, 10
    ld (4096), b
    ld c, 20
    ld (4096), c
    ld d, 30
    ld (4096), d
  ", "~{b},~{c},~{d},~{memory}"()
  ret void
}

; A simpler test using LLVM IR that should generate different source registers
define void @test_different_source_values() {
; CHECK-LABEL: test_different_source_values:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ld hl, 8192
; CHECK-NEXT:    ld (hl), 15
; CHECK-NEXT:    ld (hl), 30
; CHECK-NEXT:    ld (hl), 45
; CHECK-NEXT:    ret
; CHECK-NEXT:    .section .text,"ax",@progbits
; CHECK-NEXT:    .local .Lfunc_end1
; CHECK-NEXT:  .Lfunc_end1:
; CHECK-NEXT:    .size _test_different_source_values, .Lfunc_end1-_test_different_source_values
; This function stores different computed values to force different source registers
; The key is that after optimization, each store must preserve its original source

  %val1 = add i8 10, 5    ; This should get a different register than the next
  %val2 = add i8 20, 10   ; This should get a different register
  %val3 = add i8 30, 15   ; And this should get yet another register

  store volatile i8 %val1, i8* inttoptr (i64 8192 to i8*)
  store volatile i8 %val2, i8* inttoptr (i64 8192 to i8*)
  store volatile i8 %val3, i8* inttoptr (i64 8192 to i8*)
  ret void
}

; Test to ensure we handle the case where some stores CAN be optimized and others cannot
define void @test_mixed_optimization_safety() {
; CHECK-LABEL: test_mixed_optimization_safety:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ld hl, 12288
; CHECK-NEXT:    ld de, 1500
; CHECK-NEXT:    ld (hl), 10
; CHECK-NEXT:    ld (12288), de
; CHECK-NEXT:    ld (hl), 42
; CHECK-NEXT:    ret
; CHECK-NEXT:    .section .text,"ax",@progbits
; CHECK-NEXT:    .local .Lfunc_end2
; CHECK-NEXT:  .Lfunc_end2:
; CHECK-NEXT:    .size _test_mixed_optimization_safety, .Lfunc_end2-_test_mixed_optimization_safety
; If any store in a sequence cannot be safely converted to HL-indirect,
; the entire sequence should not be optimized to maintain correctness

  %val1 = add i8 5, 5
  %val2 = add i16 1000, 500  ; Different size - may prevent optimization

  store volatile i8 %val1, i8* inttoptr (i64 12288 to i8*)
  ; This cast creates a potential type mismatch that the old buggy code would handle incorrectly
  %ptr = inttoptr i64 12288 to i16*
  store volatile i16 %val2, i16* %ptr
  store volatile i8 42, i8* inttoptr (i64 12288 to i8*)
  ret void
}
