; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Test for substores optimization when sequences need to be split
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s --check-prefix=OPT
; RUN: llc -mtriple=z80-none-elf+full -O2 < %s | FileCheck %s --check-prefix=NOOPT

; Test simple subsequence optimization with inline assembly breaking the sequence
define void @test_inline_assembly_break() {
; Inline assembly doesn't interfere with HL, but register allocation does affect the sequence.
;
; OPT-LABEL: test_inline_assembly_break:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 4096
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ;APP
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end0
; OPT-NEXT:  .Lfunc_end0:
; OPT-NEXT:    .size _test_inline_assembly_break, .Lfunc_end0-_test_inline_assembly_break
;
entry:
  store volatile i8 1, i8* inttoptr (i64 4096 to i8*)
  store volatile i8 2, i8* inttoptr (i64 4096 to i8*)
  call void asm sideeffect "", ""()  ; Inline assembly doesn't affect HL, sequence continues
  store volatile i8 3, i8* inttoptr (i64 4096 to i8*)
  ret void
}

; Test a store sequence containing a value sourced from HL (should stay unoptimized)
define void @test_hl_source_blocks_subsequence() {
; The second store writes the contents of HL, so the pass must bail out.
;
; OPT-LABEL: test_hl_source_blocks_subsequence:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 0
; OPT-NEXT:    ld (-32512), hl
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0x3456
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (-32512), hl
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end1
; OPT-NEXT:  .Lfunc_end1:
; OPT-NEXT:    .size _test_hl_source_blocks_subsequence, .Lfunc_end1-_test_hl_source_blocks_subsequence
;
; NOOPT-LABEL: test_hl_source_blocks_subsequence:
; NOOPT:       ; %bb.0: ; %entry
; NOOPT-NEXT:    ld hl, 0
; NOOPT-NEXT:    ld (-32512), hl
; NOOPT-NEXT:    ;APP
; NOOPT-NEXT:    ld hl, 0x3456
; NOOPT-NEXT:    ;NO_APP
; NOOPT-NEXT:    ld (-32512), hl
; NOOPT-NEXT:    ret
; NOOPT-NEXT:    .section .text,"ax",@progbits
; NOOPT-NEXT:    .local .Lfunc_end1
; NOOPT-NEXT:  .Lfunc_end1:
; NOOPT-NEXT:    .size _test_hl_source_blocks_subsequence, .Lfunc_end1-_test_hl_source_blocks_subsequence
entry:
  store volatile i16 0, i16* inttoptr (i64 33024 to i16*)
  %hl_value = call i16 asm "ld hl, 0x3456", "={hl}"()
  store volatile i16 %hl_value, i16* inttoptr (i64 33024 to i16*)
  ret void
}

; Test multiple subsequences with mixed register usage
define void @test_mixed_register_stores() {
; HL conflict from `ld a, l` splits the sequence. First store unoptimized, then 3 stores optimized.
;
; OPT-LABEL: test_mixed_register_stores:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld hl, 8192
; OPT-NEXT:    ld de, 4660
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ld (8192), de
; OPT-NEXT:    ld (hl), 4
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end2
; OPT-NEXT:  .Lfunc_end2:
; OPT-NEXT:    .size _test_mixed_register_stores, .Lfunc_end2-_test_mixed_register_stores
;
entry:
  store volatile i8 1, i8* inttoptr (i64 8192 to i8*)
  store volatile i8 2, i8* inttoptr (i64 8192 to i8*)
  store volatile i16 4660, i16* inttoptr (i64 8192 to i16*)
  store volatile i8 4, i8* inttoptr (i64 8192 to i8*)
  ret void
}

; Test cost model - when HL conflicts split the sequence
define void @test_hl_liveness_cost_model() {
; Multiple HL conflicts (ld a, l and ld a, h) split the sequence into subsequences
;
; OPT-LABEL: test_hl_liveness_cost_model:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 0
; OPT-NEXT:    add iy, sp
; OPT-NEXT:    push iy
; OPT-NEXT:    ld hl, 12288
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    ld (hl), 3
; OPT-NEXT:    ld (hl), 4
; OPT-NEXT:    ld (hl), 5
; OPT-NEXT:    ld (hl), 6
; OPT-NEXT:    pop hl
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end3
; OPT-NEXT:  .Lfunc_end3:
; OPT-NEXT:    .size _test_hl_liveness_cost_model, .Lfunc_end3-_test_hl_liveness_cost_model
;
entry:
  %hl_var = alloca i16  ; This forces HL to be live
  store volatile i8 1, i8* inttoptr (i64 12288 to i8*)
  store volatile i8 2, i8* inttoptr (i64 12288 to i8*)
  store volatile i8 3, i8* inttoptr (i64 12288 to i8*)
  store volatile i8 4, i8* inttoptr (i64 12288 to i8*)
  store volatile i8 5, i8* inttoptr (i64 12288 to i8*)
  store volatile i8 6, i8* inttoptr (i64 12288 to i8*)
  %hl_val = load i16, i16* %hl_var  ; Use the allocated variable
  ret void
}

; Test that small sequences do NOT get optimized when HL is live
define void @test_small_sequence_hl_not_live() {
; L register is used (ld a, l), making HL live. With only 2 stores, no optimization should occur.
;
; OPT-LABEL: test_small_sequence_hl_not_live:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 0
; OPT-NEXT:    add iy, sp
; OPT-NEXT:    push iy
; OPT-NEXT:    ld hl, 16384
; OPT-NEXT:    ld (hl), 1
; OPT-NEXT:    ld (hl), 2
; OPT-NEXT:    pop hl
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end4
; OPT-NEXT:  .Lfunc_end4:
; OPT-NEXT:    .size _test_small_sequence_hl_not_live, .Lfunc_end4-_test_small_sequence_hl_not_live
;
entry:
  %hl_var = alloca i16  ; This creates some stack usage but doesn't make HL live
  store volatile i8 1, i8* inttoptr (i64 16384 to i8*)
  store volatile i8 2, i8* inttoptr (i64 16384 to i8*)
  %hl_val = load i16, i16* %hl_var  ; Use the allocated variable
  ret void
}

; Test HL preservation when HL is live - should use PUSH/POP
define i16 @test_hl_preservation_required() {
; When HL is live and we have enough stores (6+), optimization should happen with preservation
;
; OPT-LABEL: test_hl_preservation_required:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 20480
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0x5678
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end5
; OPT-NEXT:  .Lfunc_end5:
; OPT-NEXT:    .size _test_hl_preservation_required, .Lfunc_end5-_test_hl_preservation_required
;
entry:
  ; Force HL to be live using inline assembly
  %hl_input = call i16 asm "ld hl, 0x5678", "={hl}"()

  ; 6 stores - meets threshold for optimization when HL is live
  store volatile i8 1, i8* inttoptr (i64 20480 to i8*)
  store volatile i8 2, i8* inttoptr (i64 20480 to i8*)
  store volatile i8 3, i8* inttoptr (i64 20480 to i8*)
  store volatile i8 4, i8* inttoptr (i64 20480 to i8*)
  store volatile i8 5, i8* inttoptr (i64 20480 to i8*)
  store volatile i8 6, i8* inttoptr (i64 20480 to i8*)

  ; Return HL value - forces HL to remain live
  ret i16 %hl_input
}

; Test that HL is NOT optimized when live but insufficient stores
define i16 @test_hl_live_insufficient_stores() {
; Only 2 stores with HL live - should NOT optimize (needs 6+)
;
; OPT-LABEL: test_hl_live_insufficient_stores:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 24576
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0x1234
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end6
; OPT-NEXT:  .Lfunc_end6:
; OPT-NEXT:    .size _test_hl_live_insufficient_stores, .Lfunc_end6-_test_hl_live_insufficient_stores
;
entry:
  ; Force HL to be live
  %hl_input = call i16 asm "ld hl, 0x1234", "={hl}"()

  ; Only 2 stores - insufficient when HL is live
  store volatile i8 1, i8* inttoptr (i64 24576 to i8*)
  store volatile i8 2, i8* inttoptr (i64 24576 to i8*)

  ; Return HL value
  ret i16 %hl_input
}

; Test H register liveness detection - HL conflict causes sequence split
define i8 @test_h_register_preservation() {
; HL conflict from `ld a, h` splits sequence. Only 5 stores in subsequence, so no optimization occurs.
;
; OPT-LABEL: test_h_register_preservation:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 28672
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld h, 0x42
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld a, h
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end7
; OPT-NEXT:  .Lfunc_end7:
; OPT-NEXT:    .size _test_h_register_preservation, .Lfunc_end7-_test_h_register_preservation
;
entry:
  ; Force H register to be live
  %h_input = call i8 asm "ld h, 0x42", "={h}"()

  ; 6 stores to trigger optimization
  store volatile i8 1, i8* inttoptr (i64 28672 to i8*)
  store volatile i8 2, i8* inttoptr (i64 28672 to i8*)
  store volatile i8 3, i8* inttoptr (i64 28672 to i8*)
  store volatile i8 4, i8* inttoptr (i64 28672 to i8*)
  store volatile i8 5, i8* inttoptr (i64 28672 to i8*)
  store volatile i8 6, i8* inttoptr (i64 28672 to i8*)

  ; Return H value
  ret i8 %h_input
}

; Test L register liveness detection - HL is live, insufficient stores for optimization
define i8 @test_l_register_preservation() {
; L register is live and used at the end. With only 6 stores but HL live, insufficient for optimization.
;
; OPT-LABEL: test_l_register_preservation:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, -32768
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld l, 0x37
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld a, l
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end8
; OPT-NEXT:  .Lfunc_end8:
; OPT-NEXT:    .size _test_l_register_preservation, .Lfunc_end8-_test_l_register_preservation
;
entry:
  ; Force L register to be live
  %l_input = call i8 asm "ld l, 0x37", "={l}"()

  ; 6 stores to trigger optimization
  store volatile i8 1, i8* inttoptr (i64 32768 to i8*)
  store volatile i8 2, i8* inttoptr (i64 32768 to i8*)
  store volatile i8 3, i8* inttoptr (i64 32768 to i8*)
  store volatile i8 4, i8* inttoptr (i64 32768 to i8*)
  store volatile i8 5, i8* inttoptr (i64 32768 to i8*)
  store volatile i8 6, i8* inttoptr (i64 32768 to i8*)

  ; Return L value
  ret i8 %l_input
}

; Test edge case: HL used between stores but not live after
define void @test_hl_used_between_not_live() {
; First store should remain unoptimized (single store before inline asm)
; Inline assembly uses HL but doesn't make it live after
; Subsequent stores should be optimized without HL preservation
;
; OPT-LABEL: test_hl_used_between_not_live:
; OPT:       ; %bb.0: ; %entry
; OPT-NEXT:    ld iy, 8192
; OPT-NEXT:    ld (iy), 1
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld hl, 0x1234
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ;APP
; OPT-NEXT:    ld (0x9000), hl
; OPT-NEXT:    ;NO_APP
; OPT-NEXT:    ld (iy), 2
; OPT-NEXT:    ld (iy), 3
; OPT-NEXT:    ld (iy), 4
; OPT-NEXT:    ld (iy), 5
; OPT-NEXT:    ld (iy), 6
; OPT-NEXT:    ret
; OPT-NEXT:    .section .text,"ax",@progbits
; OPT-NEXT:    .local .Lfunc_end9
; OPT-NEXT:  .Lfunc_end9:
; OPT-NEXT:    .size _test_hl_used_between_not_live, .Lfunc_end9-_test_hl_used_between_not_live
;
entry:
  ; First store - will be left unoptimized (single store before inline asm)
  store volatile i8 1, i8* inttoptr (i64 8192 to i8*)

  ; Use HL temporarily - this breaks the sequence but doesn't make HL live after
  %temp = call i16 asm sideeffect "ld hl, 0x1234", "={hl}"()
  call void asm sideeffect "ld (0x9000), hl", "{hl}"(i16 %temp)

  ; More stores - should be optimized together without HL preservation
  ; because HL is not live after this sequence
  store volatile i8 2, i8* inttoptr (i64 8192 to i8*)
  store volatile i8 3, i8* inttoptr (i64 8192 to i8*)
  store volatile i8 4, i8* inttoptr (i64 8192 to i8*)
  store volatile i8 5, i8* inttoptr (i64 8192 to i8*)
  store volatile i8 6, i8* inttoptr (i64 8192 to i8*)

  ret void
}
